config/routes.rb
TimeAuction::Application.routes.draw do
  resources :password_resets

  root to: 'static_pages#index'
  resources :users, :except => :index do
    resources :photos, :only => [:create]
  end
  resources :sessions, :only =>[:new, :create, :destroy]
  resources :bids, :only => [:create]
  resources :auctions do
    resources :photos, :only => [:create]
    resources :comments, :only => [:create, :destroy]
    get :comments, :on => :member
  end
  resources :categories, :only => [:index]
  resources :charities

  get '/about' => "static_pages#about", :layout => false
  get '/rules' => "static_pages#rules", :layout => false

  match 'auth/facebook', as: 'fb_login'
  match 'auth/:provider/callback', to: 'sessions#create_identity'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout' # maybe not required
  

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  attr_accessible :auction_id, :charity_id, :time, :user_id
  validates :auction_id, presence: true
  validates :user_id, presence: true
  validates :time, presence: true
  belongs_to :user
  belongs_to :auction
  belongs_to :charity
  validate :highest_in_auction
  validate :under_max

  def to_json
    { name: self.user.name }.to_json
  end

  def description
    self.time.to_s + " hours"
  end

  private
    def highest_in_auction
      if self.auction && self.auction.bids.where("time >= ?", self.time).any?
        self.errors.add(:time, 'must be greater than the highest bid')
      end
    end

    def under_max
      if self.time > 500
        self.errors.add(:time, 'Bid was too high')
      end
    end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def create
    @bid = Bid.new params[:bid]
    @bid.user = current_user
    @auction = @bid.auction
    @bids = @auction.bids

    charity = Charity.find_or_create_by_name(params[:bid][:charity_id].downcase.titleize)

    @bid.charity = charity

    if @bids == []
      @last_bid_time = 0
    else
      @last_bid_time = @bids.last.time
    end
    
    if @bid.time.nil?
      render text: 'Please enter the number of hours you wish to bid!', status: :unprocessable_entity and return
    end

    if @bid.time <= @last_bid_time
      render text: 'Your bid must be higher than the current highest bid!', status: :unprocessable_entity and return
    end

    if @bid.auction.end_date <= Time.now
      render text: 'Sorry!  This auction has ended.  Try another one?', status: :unprocessable_entity and return
    end

    sleep 2

    if @bid.save
      # EmailWorker.perform_async(@bids.reload.map(&:id).uniq)
      
      render text: render_to_string(partial: 'bid', locals: { bid: @bid })
    else
      render text: @bid.errors.full_messages.join(','), status: :unprocessable_entity
    end
  end
end

app/views/bids/_bid.html.erb
<tr>
  <td><%= avatar(bid.user, options = {height: 32, width: 32}) %> <%= link_to bid.user.name, bid.user %></td> 
  <td><%= bid.time %></td>
  <td>
    <% if bid.charity %>
      <%= link_to bid.charity.name.truncate(28), bid.charity %>
    <% else %>
      None Specified
    <% end %>
  </td>
  <td><%= time_ago_in_words(bid.created_at) %> ago</td>
</tr>

app/views/bids/_form.html.erb
<%= form_for :bid, url: bids_path, remote: true, html: { id: "new_bid_form", class: "hide" } do |f| %>
  <div class="pop-up">
    <div class="pop-up-left">
      <h1>Making a bid</h1>
      <h4>Thank you for your interest in volunteering!</h4>
      <p>Here's what you need to know:</p>
      <ol>
        <li>You are awesome.</li>
        <li>You need to bid higher than <%= @auction.highest_bid.description %>.</li>
        <li>If you win, you need to complete your hours by <%= @auction.deadline.strftime('%b %d, %Y') %>.</li>
        <li>This needs to be a new volunteering commitment.</li>
        <li>We will call your charity to validate your awesome work.</li>
        <li>Then you will get your prize :)</li>
      </ol>
    </div>
    <div class="pop-up-right">
      <%= cl_image_tag @auction.photos.first.url, :width => 200, :height => 150 unless @auction.photos == [] %>
      <h4><%= @auction.title %></h4>
    </div>
    <div class="pop-up-bottom">
      I, <%= current_user.name if current_user %>, will bid <span><%= f.text_field :time, placeholder: "Number", :class => "input-small" %> hours.</span>
      <span>Where will you volunteer?</span> <span><%= f.text_field :charity_id, :title => "Select a charity or enter a new one", :placeholder => "Charity name (optional)" %></span>
      <%= f.hidden_field :auction_id, value: @auction.id %>

      <div>By clicking below, you agree to the official <%= link_to "Time Auction rules", rules_path %>.</div><br>
      <div><button type="button" class="btn btn-success btn-large commit-to-bid" data-loading-text="Submitting...">Submit Bid</button></div>
    </div>
  </div>
<% end %>

app/views/bids/_highest_bid.html.erb
<div class="bid-time">
  <div id="hours"><%= @auction.highest_bid.time %></div>
  <div id="hours">Hours</div>
</div>
<div class="highest-bidder">
  By <%= link_to @auction.highest_bid.user.name, user_path(@auction.highest_bid.user) if @auction.highest_bid %>
</div>

app/views/bids/_success_popup.html.erb
<div id='bid_success_popup' class='hide'>
  <div class="success-pop-content">
    <h1>Thank you<%=", " + current_user.name if current_user %>!</h1>
    <br>
    <br>
    <h3>We love you.</h3>
    <br>
    <br>
    <p class='errors'></p>
    <div class="social-buttons">
    <!-- Facebook -->
      <span class="fb-button"><fb:share-button href="http://www.fbrell.com" type="button"></fb:share-button></span>
    <!--
    May need to do something like this to actually change the 'identity' model in
    our db:

    <fb:login-button scope="publish_stream">
      Post on facebook (requires login)
    </fb:login-button> -->

    <!-- Twitter -->
      <span class="tw-button"><a href="https://twitter.com/share" class="twitter-share-button" data-url="http://TimeAuction.org/auctions/<%= @auction.id %>" data-text="I just bid charity hours at Time Auction-- can you pledge more?" data-size="large">Tweet</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></span>
    </div>
    <hr/>
    <div>
      <button id="success_popup_close" class='btn btn-success btn-large'>Close</button>
    </div>
  </div>
</div>