config/routes.rb
TimeAuction::Application.routes.draw do
  resources :password_resets

  root to: 'static_pages#index'
  resources :users, :except => :index do
    resources :photos, :only => [:create]
  end
  resources :sessions, :only =>[:new, :create, :destroy]
  resources :bids, :only => [:create]
  resources :auctions do
    resources :photos, :only => [:create]
    resources :comments, :only => [:create, :destroy]
    get :comments, :on => :member
  end
  resources :categories, :only => [:index]
  resources :charities

  get '/about' => "static_pages#about", :layout => false
  get '/rules' => "static_pages#rules", :layout => false

  match 'auth/facebook', as: 'fb_login'
  match 'auth/:provider/callback', to: 'sessions#create_identity'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout' # maybe not required
  

end

app/models/auction.rb
require 'date'

class Auction < ActiveRecord::Base
  attr_accessible :category_id, :description, :start_date, :end_date, :title, :winner_id, :verified_time, :deadline, :photos_attributes
  has_many :bids, :order => 'bids.created_at DESC', :dependent => :destroy
  has_many :users, through: :bids
  has_many :photos, :as => :imageable, :dependent => :destroy
  has_many :comments, :order => 'comments.created_at DESC', :dependent => :destroy


  belongs_to :category
  accepts_nested_attributes_for :photos 
  before_validation :set_dates
  before_create :initial_verified_time
  validates :deadline, :presence => true
  validates :title, :presence => true
  validates :description, :presence => true
  validates :start_date, :presence => true
  validates :end_date, :presence => true
  validates :category_id, :presence => true
  # validate :valid_dates

  def self.check_auction_finished
    # scope find finished bids
    # auctions = Auction.finished
    @auctions = Auction.all
    @finished = @auctions.select { |auction| auction.end_date < Time.now && auction.bids.any? && !auction.winner_id }
    
    # set winner_id to owner of highest bid for each auction
    @finished.each do |auction|
      auction.winner_id = auction.highest_bid.user.id
      auction.save # what happens if this reutrns false
      
      # identify unique bidders of auction
      uniq_users = auction.users.uniq # is this in rails?
      bid_ids = []
      uniq_users.each do |user|
        # find the id of the last bid placed, for this auction
        bid_ids << user.bids.where(:auction_id => auction.id).order("time DESC").first.id
      end

      # returning finished auction!!

      # AuctionEndWorker.perform_async(bid_ids)
    end
  end

  def highest_bid
    self.bids.order("time DESC").first || NullBid.new
  end

  class NullBid < Bid
    def time
      0
    end
  end

  def started?
    Time.now >= self.start_date
  end

  def complete?
    self.winner_id
  end

  def parse_dates(params)
    self.start_date = DateTime.parse(params[:auction].delete(:start_date).split('/').rotate(-1).join(''))
    self.end_date = DateTime.parse(params[:auction].delete(:end_date).split('/').rotate(-1).join(''))
  end

  private

  def initial_verified_time
    self.verified_time = 0
  end

  def valid_dates
    errors.add(:base, "Start date must be before end date") unless self.start_date < self.end_date
  end

  def set_dates
    self.deadline = self.end_date + 1.month if self.end_date
  end

end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_filter :load_auction, :only => [:show, :edit, :update, :destroy, :comments]

  def new
    @auction = Auction.new
    @photo = @auction.photos.build
  end

  def create

    unless params[:auction][:start_date].blank? && params[:auction][:end_date].blank?
      params[:auction][:start_date] = DateTime.parse(params[:auction][:start_date].split('/').rotate(-1).join(''))
      params[:auction][:end_date] = DateTime.parse(params[:auction][:end_date].split('/').rotate(-1).join(''))
    end

    @auction = Auction.new params[:auction]
    proper_date = @auction.start_date < @auction.end_date if @auction.start_date && @auction.end_date

    unless proper_date
      flash.now[:errors] = "Start date must be before end date"
    end

    if @auction.save && proper_date
      redirect_to auction_path @auction
    else
      if flash.now[:errors]
        flash.now[:errors] += ". "
        flash.now[:errors] += @auction.errors.full_messages.join(". ")
      else
        flash.now[:errors] = @auction.errors.full_messages.join(". ")
      end
      render :new
    end
  end

  def show
    @winner = User.find(@auction.winner_id) if @auction.winner_id
    @winning_time = @auction.bids.last.time if @winner
    store_location
    @comments = paginated_comments
    @bids = @auction.bids
    @all_charities = Charity.all.map { |charity| charity.name }
  end

  def edit
    redirect_to root_path unless current_user.admin
  end

  def update
    @auction.parse_dates(params)
    params[:auction].delete(:start_date) && params[:auction].delete(:end_date)

    proper_date = @auction.start_date < @auction.end_date if @auction.start_date && @auction.end_date

    if @auction.winner_id
      auction_winner = User.find(@auction.winner_id) 
      auction_winner.time_donated += (params[:auction][:verified_time].to_i - @auction.verified_time)
      auction_winner.save
    end

    unless proper_date
      flash.now[:errors] = "Start date must be before end date"
    end

    if @auction.update_attributes(params[:auction]) && proper_date
      redirect_to auction_path(@auction)
    else
      @categories = Category.all
      if flash.now[:errors]
        flash.now[:errors] += ". "
        flash.now[:errors] += @auction.errors.full_messages.join(". ")
      else
        flash.now[:errors] = @auction.errors.full_messages.join(". ")
      end
      render 'edit'
    end
  end

  def destroy
    flash[:success] = "You have successfully deleted #{@auction.title}"
    Auction.destroy(@auction)
    redirect_to user_path(current_user)
  end

  def comments
    @comments = paginated_comments
    render :partial => 'comments/paginated_comments'
  end

  private
  def load_auction
    @auction = Auction.find(params[:id])
  end

  def paginated_comments
    @auction.comments.paginate(page: params[:page], :per_page => 10)
  end
end

app/views/auctions/_form.html.erb
<div class="creation_container">
  <h1 id="creation_title"><%= @title %></h1>
    <div class="auction-category">
    <%= link_to "> Back to auction", auction_path(@auction) if @auction.valid? %>
  </div>
  <div class="creation_form">
    <%= form_for @auction do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, :required => true, :autofocus => true %>
    <%= f.label :description %>
    <%= f.text_area :description, :required => true %>
    <%= f.label :category %>
    <%= collection_select(:auction, :category_id, Category.all, :id, :name ) %>
    <%= f.label :start_date, "Auction Start Date" %>
    <%= f.text_field :start_date, html: { id: 'datepicker' }, :required => true %>
    <%= f.label :end_date, "Auction End Date" %>
    <%= f.text_field :end_date, html: { id: 'datepicker' }, :required => true %>
    <span class="hide" id="verified_time">
      <%= f.label :verified_time %>
      <%= f.text_field :verified_time %>
    </span>
    <div class="upload">
      <%= f.fields_for :photos, :html => { multipart: true } do |builder| %>
        <label for="file">Apply Photo</label>
        <% if @title == "Add an Auction" %>
          <%= builder.file_field :url, :required => true %>
        <% else %>
          <%= builder.file_field :url %>
        <% end %>
      <% end %>
    </div>
      <%= f.submit @submit, :class => "user_form_button" %>
    <% end %>
    <%= @delete_button if @delete_button %>
  </div>
</div>

app/views/auctions/_ribbon.html.erb
<div class="ribbon-edge-topleft"></div>
<div class="ribbon-edge-topright"></div>
<div class="ribbon-edge-bottomleft"></div>
<div class="ribbon-edge-bottomright"></div>
<div class="ribbon-back-left"></div>
<div class="ribbon-back-right"></div>

app/views/auctions/edit.html.erb
<% @title = "Edit Auction" %>

<% @delete_button = button_to "Delete Auction", auction_path(@auction), :method => 'delete', :class => 'user_form_button', :id => "delete_button" %>

<%= render 'form', :locals => { :title => @title, :delete_button => @delete_button, :auction => @auction } %>

app/views/auctions/new.html.erb
<% @title = "Add an Auction" %>

<% @submit = "Create Auction" %>
<%= render 'form', :locals => { :title => @title, :submit => @submit } %>

app/views/auctions/show.html.erb
<!-- LIGHTBOX -->
<script src="/assets/bootstrap-button.js?body=1" type="text/javascript"></script>
<div class="row">
  <div class="span10 offset1 hidden-bid-partial">
    <%= render 'bids/form' %>
  </div>
</div>
<div class="row">
  <div class="span10 offset1">
    <%= render 'bids/success_popup' %>
  </div>
</div>
<div class="row">
  <div class="span10 offset1 hide" id='spinner'>
    <%= image_tag 'ajax_loader_red_64.gif' %>
  </div>
</div>

<div class="row">
  
<!-- TITLE -->
  <div class="span12">
    <div class="auction-category">
      <%= link_to '> ' + @auction.category.name, "/categories?tab=#{@auction.category.name}" %>
    </div>
    <div class="auction-title">
      <h1><%= @auction.title %></h1>
    </div>
    <div class="edit-as-admin">
      <%= link_to "Edit as admin", edit_auction_path(@auction) if current_user && current_user.admin %>
    </div>
    <hr>
  </div>

<!-- LEFT SIDE CONTENT -->

  <div class="span8" id="auction">
    <div class="auction-photo shadow">
      <%= cl_image_tag @auction.photos.first.url, :width => 600, :height => 450 unless @auction.photos == [] %>
    </div>

<!-- TABS -->

    <ul class="nav nav-tabs">
      <li class="active">
        <a href="#auction-description" data-toggle="tab">Description</a></li>
      <li>
        <a href="#auction-bid-history" data-toggle="tab" id="bidsTab">Bid History</a>
      </li>
      <li>
        <a href="#auction-comments" data-toggle="tab" id="commentsTab">Comments (<span id="commentCount"><%= @comments.count %></span>)</a>
      </li>
    </ul>

<!-- DESCRIPTION -->

    <div class="tab-content">
      <div class="tab-pane active" id="auction-description"> 
        <h3>Auction Description</h3>
          <%= simple_format(@auction.description) %>
      </div>

<!-- BID HISTORY -->

      <div class="tab-pane" id="auction-bid-history">
        <h3>Bid History</h3>
        <table class="bids">
          <tr>
            <th>Name</th>
            <th>Hrs</th>
            <th>Charity</th>
            <th>Posted</th>
          </tr>
          <%= render @bids %>  
        </table>
      </div>

<!-- COMMENTS -->
      <div class="tab-pane" id="auction-comments">
        <h3>Auction Comments</h3>
        <ul class="comments" id="commentList">
          <%= render 'comments/paginated_comments' %>
        </ul>
          <% if current_user %>
          <li id='comment_errors'></li>
            <%= form_for [@auction, Comment.new], :remote => true do |f| %>
            <%= f.text_area :content, :rows => 5, :class => "desc_box", :placeholder => "Comment on this auction" %>
            <%= f.submit "Add Comment", :class => "btn btn-large btn-danger" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  
<!-- RIGHT SIDE CONTENT -->

  <div class="span4">
    <div class="highest-bid">
      <% if @auction.bids == [] %>
        <div class="highest-bid-title ribbon">
          <div class="ribbon-front">
            <div class='no-bids-yet'>No bids yet</div>
          </div>
          <%= render 'ribbon' %>
        </div>
        <div class="bid-time">
          <div id="hours">0</div>
          <div id="hours">Hours</div>
        </div>
        <div class="highest-bidder">
          Be the first to bid <%= "when it starts!" unless @auction.started? %>
        </div>
        
      <% else %>

        <% if @winner %>
          <div class="highest-bid-title ribbon">
            <div class="ribbon-front">
              Winning Bid
            </div>
            <%= render 'ribbon' %>
          </div>
            <%= render 'bids/highest_bid' %>
        <% else %>
          <div class="highest-bid-title ribbon">
            <div class="ribbon-front">
              Highest Bid
            </div>
            <%= render 'ribbon' %>
          </div>
            <%= render 'bids/highest_bid' %>
        <% end %>

      <% end %>
    </div>

    <div class='you-highest<%= ' hide' unless @auction.highest_bid && @auction.highest_bid.user == current_user && !@auction.winner_id %>'>
        <h3>You're Currently the Top Bidder!</h3>
        
        <!-- Twitter script -->
        <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://TimeAuction.org/auctions/<%= @auction.id %>" data-text="I'm winning for charity at Time Auction-- try to top me!" data-count="none">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    </div>

<!-- BID BUTTON -->

    <div class='main-bid-button'>
      <div id="overlay"></div>

      <% if current_user && (!@auction.started? && !@auction.complete?) || (@auction.started? && @auction.complete?) %>
      <% elsif !current_user %>
        <%= button_to 'Signin to Bid', new_user_path, method: :get %>
      <% else %>
        <div id="trigger"><button class="btn btn-danger btn-large bid-button">Bid Hours</button></div>
      <% end %>
    </div>

<!-- AUCTION DETAILS -->

    <div class='auction-details'>
      <div class="detail-box">
        <h3>Auction Start Date</h3>
        <p>
          <%= @auction.start_date.strftime('%b %d, %Y') %>
        </p>
      </div>
      <div class="detail-box">
        <% if Time.now < @auction.end_date %> <!-- Auction Hasn't Ended -->
          <h3>Auction End Date</h3>
          <p>
            <%= @auction.end_date.strftime('%b %d, %Y') %>
          </p>
        <% else %> <!-- Auction Ended  -->
          <h3>Auction Has Ended</h3>
          <p>
            <%= @auction.end_date.strftime('%b %d, %Y') %>
          </p>
          <p>
            <%= link_to "Check out other auctions", categories_path %>
          </p>
        <% end %>
      </div>
      <div class="detail-box">
        <% if Time.now < @auction.deadline %>  <!-- Auction Ended  -->
          <h3>Volunteer Deadline</h3>
          <p>
            <%= @auction.deadline.strftime('%b %d, %Y') %>
          </p>
        <% else %>  <!-- Auction Ultimate Complete  -->
          <h3>Volunteer Status</h3>
          <p>
            <%= "#{@auction.verified_time.to_s} of #{@winning_time} hours completed!" unless @auction.verified_time.nil? %> <%= "Thank you " if @winner %><%= link_to @winner.name,  user_path(@winner) if @winner %>
          </p>
        <% end %>
      </div>
    </div>
    <div class="facebook_links">
      <fb:like send="true" width="296" show_faces="true"></fb:like>
    </div>
  </div>

</div>

<div class="hide all-charities"><%= @charities %></div>

<!-- 
winner user not_start => no case
winner no_user no_start => no case

winner user start => no button
no_winner user no_start => no button

winner no_user start => sign up button
no_winner no_user start => sign up button
no_winner no_user no_start => sign up button

no_winner user start => bid button
 -->