config/routes.rb
TimeAuction::Application.routes.draw do
  resources :password_resets

  root to: 'static_pages#index'
  resources :users, :except => :index do
    resources :photos, :only => [:create]
  end
  resources :sessions, :only =>[:new, :create, :destroy]
  resources :bids, :only => [:create]
  resources :auctions do
    resources :photos, :only => [:create]
    resources :comments, :only => [:create, :destroy]
    get :comments, :on => :member
  end
  resources :categories, :only => [:index]
  resources :charities

  get '/about' => "static_pages#about", :layout => false
  get '/rules' => "static_pages#rules", :layout => false

  match 'auth/facebook', as: 'fb_login'
  match 'auth/:provider/callback', to: 'sessions#create_identity'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout' # maybe not required
  

end

app/views/partials/_facebook_core.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=295600783906928";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/partials/_footer.html.erb
<div class="footer">
  <div class="footerContainer">
    <div class="footerContent">
      <p><strong>&copy; 2013 by these Dev Bootcamp students:</strong></p>
      <hr id="footer">
      <li><%= link_to 'David Wen', 'https://github.com/Dawenster' %></li>
      <li><%= link_to 'Kevin Ko', 'https://github.com/heyimkko' %></li>
      <li><%= link_to 'Philip Woo', 'https://github.com/jhw1202' %></li>
      <li><%= link_to 'J Connolly', 'https://github.com/jsconnolly' %></li>
    </div>
    <div class="footerContent">
      <p><strong>Additional Resources:</strong></p>
      <hr id="footer">
      <li><%= link_to 'Official Rules', rules_path %></li>
      <li><%= link_to 'Source', 'https://www.github.com/Dawenster/time_auction' %></li>
      <li><%= link_to 'About Us', about_path %></li>
      <li><%= link_to 'Dev Bootcamp', 'http://www.devbootcamp.com' %></li>
      
    </div>
    <div class="footerContent">
      <p><strong>Connect With Us:</strong></p>
      <hr id="footer">
      <li><%= mail_to 'team@timeauction.org', 'Contact Team' %></li>
      <a href="https://twitter.com/share" class="twitter-share-button" id="twitter_footer" data-url="http://TimeAuction.org" data-text="Check out Time Auction to bid volunteer hours for awesome stuff.">Tweet</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
      <div class="fb-like" data-href="http://www.TimeAuction.org" data-send="false" data-width="450" data-show-faces="true" data-colorscheme="dark">
      </div>
    </div>
  </div>
</div>

app/views/partials/_guest_footer.html.erb
<div class="footerContent">
  <%= link_to 'Sign Up', new_user_path, :class => 'footerSignUp' %>
  <%= link_to 'Login', new_session_path, :class => 'footerSignUp' %>
</div>

app/views/partials/_logged_in_footer.html.erb
<div class="footerContent">
  <%= link_to 'Browse Auctions', categories_path, :class => 'footerSignUp' %>
  <%= link_to 'My Profile', user_path(current_user), :class => 'footerSignUp' %>
</div>

app/views/partials/_logged_in_user_nav.html.erb
<% if current_user.admin %>
<li class="dropdown">
  <a class="dropdown-toggle" href="#" id="navName">Create</a>
  <ul class="dropdown-menu">
    <li><%= link_to 'Auction', new_auction_path %></li>
    <li><%= link_to 'Charity', new_charity_path %></li>
  </ul>
</li>
<% end %>
<li><%= navatar(current_user) %></li>
<li>
  <%= link_to "Logout", session_path(current_user), :method => :delete, :id => "navName" %>
</li>

app/views/partials/_nav.html.erb
<nav>
  <ul id="kstrap-navbar">
    <%= link_to "TimeAuction", root_path, id: 'logo' %>
    <li>
      <%= link_to "About", about_path, :id => "navName" %>
    </li>
    <li class="dropdown">
        <a class="dropdown-toggle" href="#" id="navName">Browse</a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Auctions', categories_path %></li>
          <li><%= link_to 'Charities', charities_path %></li>
        </ul>
      </li>
    <% if current_user %>
      <%= render 'partials/logged_in_user_nav' %>
    <% else %>
      <li><%= link_to "Login", new_session_path, :id => "navName" %></li>
      <li><%= link_to "Sign up", new_user_path, :id => "navName" %></li>
    <% end %>
  </ul>
</nav>
<div class="backNav">
</div>

app/views/partials/_static_header.html.erb
<!DOCTYPE html>
<html>
<html xmlns:fb="http://ogp.me/ns/fb#">
<head>
  <title>TimeAuction</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Oleo+Script|PT Sans Narrow|Open+Sans:400,300|Open+Sans+Condensed:300|Lato:300,400,700,700italic,900' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'partials/facebook_core' %>
  <%= render 'partials/nav' %>