config/routes.rb
TimeAuction::Application.routes.draw do
  resources :password_resets

  root to: 'static_pages#index'
  resources :users, :except => :index do
    resources :photos, :only => [:create]
  end
  resources :sessions, :only =>[:new, :create, :destroy]
  resources :bids, :only => [:create]
  resources :auctions do
    resources :photos, :only => [:create]
    resources :comments, :only => [:create, :destroy]
    get :comments, :on => :member
  end
  resources :categories, :only => [:index]
  resources :charities

  get '/about' => "static_pages#about", :layout => false
  get '/rules' => "static_pages#rules", :layout => false

  match 'auth/facebook', as: 'fb_login'
  match 'auth/:provider/callback', to: 'sessions#create_identity'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout' # maybe not required
  

end

app/models/charity.rb
class Charity < ActiveRecord::Base
  attr_accessible :name, :description, :photos_attributes
  validates :name, :presence => true
  validates :name, :uniqueness => true

  has_many :bids
  has_many :photos, :as => :imageable, :dependent => :destroy
  accepts_nested_attributes_for :photos

  def self.all_names
    all.map(&:name)
  end
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  def index
    @charities = Charity.all

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @charities }
    end
  end

  def new
    @charity = Charity.new
    @photo = @charity.photos.build
  end

  def create
    params[:charity][:name] = params[:charity][:name].downcase.titleize if params[:charity][:name]
    @charity = Charity.new(params[:charity])

    if @charity.save
      redirect_to charity_path(@charity)
    else
      flash.now[:errors] = @charity.errors.full_messages.join(". ")
      render 'new'
    end
  end

  def show
    @charity = Charity.find(params[:id])
    @volunteers = @charity.bids.map { |bid| bid.user }.uniq
  end

  def edit
    @charity = Charity.find(params[:id])
    @photo = @charity.photos.build
  end

  def update
    @charity = Charity.find(params[:id])
    if @charity.update_attributes(params[:charity])
      redirect_to charity_path(@charity)
    else
      flash.now[:errors] = @charity.errors.full_messages.join(". ")
      render 'edit'
    end
  end

  def destroy
    @charity = Charity.find(params[:id])
    flash[:success] = "You have successfully deleted #{@charity.name}"
    Charity.destroy(@charity)
    redirect_to user_path(current_user)
  end
end

app/views/charities/_form.html.erb
<div class="creation_container">
  <h1 id="creation_title"><%= @title %></h1>
    <div class="auction-category">
      <%= link_to "> Back to charity", charity_path(@charity) if @charity.valid? %>
    </div>
  <div class="creation_form">
    <%= form_for @charity do |f| %>
      <%= f.label :name, 'Charity name', :autofocus => true %>
      <%= f.text_field :name %>
      <%= f.label :description, 'Describe the work that the charity does' %>
      <%= f.text_area :description %>
      <div class="upload">
        <%= f.fields_for :photos, :html => { multipart: true } do |builder| %>
        <label for="file">Attach a related photo to this charity</label>
        <% if @title == "Add a Charity" %>
          <%= builder.file_field :url, :required => true %>
        <% else %>
          <%= builder.file_field :url %>
        <% end %>
      <% end %>
    </div>
      <%= f.submit @submit, :class => "user_form_button" %>
    <% end %>
    <% if current_user && current_user.admin %>
      <%= @delete_button if @delete_button %>
    <% end %>
  </div>
</div>

app/views/charities/edit.html.erb
<% @title = "Edit Charity" %>
<% @delete_button = button_to "Delete Charity", charity_path(@charity), :method => 'delete', :class => 'user_form_button', :id => "delete_button" %>
<%= render 'form', :locals => { :title => @title, :delete_button => @delete_button, :charity => @charity } %>

app/views/charities/index.html.erb
<div class="category-display" id="auction">
  <% @charities.each do |charity| %>
    <div class="auction-column">
      <% if charity.photos.any? %>
        <%= link_to (cl_image_tag charity.photos.last.url, width: 300, height: 200, :class => "browse-photo", :crop => :fill), charity %>
      <% else %>
        <%= link_to (image_tag '/assets/charity_default.jpg', :class => "browse-photo", width: 300, height: 200), charity %>
      <% end %>
      <p class="charity-name">
        <%= link_to charity.name.truncate(28), charity %>
      </p>
      <p class="charity-description">
        <% if !charity.description.blank? && charity.description.length >= 40 %>
          <%= charity.description.truncate(68) %>
        <% elsif !charity.description.blank? && charity.description.length < 40 %>
          <%= charity.description %><BR>
          (Short description - <%= link_to "Help edit this charity", edit_charity_path(charity) %>)
        <% else %>
          (No description yet)<BR>
          <%= link_to "Help edit this charity", edit_charity_path(charity) %>
        <% end %>
      </p>
    </div>
  <% end %> 
</div>

app/views/charities/new.html.erb
<% @title = "Add a Charity" %>
<% @submit = "Create Charity" %>
<%= render 'form', :locals => { :title => @title, :submit => @submit } %>

app/views/charities/show.html.erb
<div class="row">
  <div class="span4">
    <% if @charity.photos.any? %>
      <%= cl_image_tag @charity.photos.last.url, :width => 300, :height => 200 unless @charity.photos == [] %>
    <% else %>
      <div class="no-charity-photo">
        No logo yet for this charity<BR>
        Help upload one: <%= link_to "Edit", edit_charity_path(@charity) %>
      </div>
    <% end %>
    <h3>Volunteers</h3>
    <% if @volunteers.any? %>
      <% @volunteers.each do |volunteer| %>
        <div><%= avatar(volunteer) %></div>
      <% end %>
    <% else %>
      No volunteers yet - be the first!<BR>
      Check out some <%= link_to "auctions", categories_path %> you can bid on.
    <% end %>
  </div>
  <div class="span8">
    <div>
      <h1><%= @charity.name %></h1>
    </div>
    <div>
      <p><%= simple_format(@charity.description) %></p>
      <div><%= link_to 'Edit', edit_charity_path(@charity), :class => "edit-charity", :title => "Help us edit information on this charity" %></div>
    </div>
  </div>
</div>